accentor/android

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumsFragment.kt
=> Make sure play next adds in the correct position

app/src/main/res/layout/content_main.xml
=> Fix main content overlapping with bottom bar

app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerFragment.kt
=> Always start playing when clicking in the queue

app/src/main/res/layout/queue_list_item.xml
=> Fix long names in queue pushing out track length

app/schemas/me.vanpetegem.accentor.data.AccentorDatabase/6.json, app/src/main/java/me/vanpetegem/accentor/data/AccentorDatabase.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/Album.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumDao.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/DbAlbum.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/Artist.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/ArtistDao.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/DbArtist.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/DbTrack.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/Track.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackDao.kt
=> Use normalized properties for sorting

app/build.gradle, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumDao.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackDao.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackRepository.kt, app/src/main/java/me/vanpetegem/accentor/media/MediaSessionConnection.kt, app/src/main/java/me/vanpetegem/accentor/media/MusicService.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumsFragment.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumsViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/PlayQueueAdapter.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerFragment.kt
Depends on https://github.com/accentor/api/pull/82.
=> Performance improvements

.github/workflows/release.yml
=> Add workflow to build signed APK on version tag push

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
re #103 
This one is slightly difference from web/api since it doesn't make sense to ask for desktop or smartphone browser
=> Add issue template for bug_report and feature_request

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Similar to https://github.com/accentor/web/pull/530
=> Update pull request and issue templates

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumCardAdapter.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistCardAdapter.kt
=> Make first-character-getter for fast scrolling view unicode-aware

app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerFragment.kt, app/src/main/res/layout/fragment_player_view.xml
=> Fix long track titles filling the entire player view

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumCard.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/CurrentTrackInfo.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/Queue.kt
=> De-emphasize some content

app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerOverlay.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/ToolBar.kt
=> Add custom layout for landscape player

app/src/main/java/me/vanpetegem/accentor/ui/player/Controls.kt
=> Allow seek slider to actually be used as a slider

app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumDao.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumRepository.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeFragment.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/Controls.kt, app/src/main/java/me/vanpetegem/accentor/ui/util/Timer.kt, app/src/main/res/values/strings.xml
=> Add home view

app/src/main/java/me/vanpetegem/accentor/data/albums/Album.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/Track.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackDao.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackRepository.kt, app/src/main/java/me/vanpetegem/accentor/media/MediaSessionConnection.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumsViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistCard.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistGrid.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistView.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistsViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/res/values/strings.xml
=> Add artist view

app/src/main/java/me/vanpetegem/accentor/ui/util/FastScrollableGrid.kt
=> Make sure there is always a minimum of two columns on the grid

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumView.kt
=> Limit maximum lines for title and artist on album details view

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumView.kt
=> Show release and edition on album detail page

app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerOverlay.kt
=> Don't be overeager in closing the player

app/src/main/java/me/vanpetegem/accentor/data/artists/ArtistRepository.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeFragment.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeViewModel.kt, app/src/main/res/values/strings.xml
=> Add artists to home view

.github/workflows/ci.yml
Make sure actions also run on external pull request.
=> Also run CI actions on pull request

app/src/main/java/me/vanpetegem/accentor/media/MusicService.kt
=> Make sure skipping to the previous track/start of track is always allowed

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumCard.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumView.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistView.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerOverlay.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/Queue.kt, app/src/main/java/me/vanpetegem/accentor/ui/tracks/TrackRow.kt, app/src/main/res/values/strings.xml
=> Add artist and album links where relevant

app/src/main/java/me/vanpetegem/accentor/ui/player/Queue.kt
=> Scroll to current track in queue on open

app/schemas/me.vanpetegem.accentor.data.AccentorDatabase/8.json, app/src/main/java/me/vanpetegem/accentor/api/plays/Play.kt, app/src/main/java/me/vanpetegem/accentor/data/AccentorDatabase.kt, app/src/main/java/me/vanpetegem/accentor/data/codecconversions/CodecConversionRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/Play.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/PlayRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/UnreportedPlay.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/UnreportedPlayDao.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackRepository.kt, app/src/main/java/me/vanpetegem/accentor/media/MusicService.kt
If a play was not reported due to a network error, it is saved to the local database and retried when the next play is (successfully) reported.
Fixes #199.
Tested the following scenario's:
* Transitioning from one track to the next should create a play.
* Transitioning from one track to itself (on repeat) should create a play.
* Skipping to the next track should not create a play.
* Stopping playback should not create a play.
* Playback stopping due to the end of the playlist being reached naturally should create a play.
=> Report plays

app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerOverlay.kt
=> Don't activate landscape player when in multiwindow mode

app/src/main/java/me/vanpetegem/accentor/media/MediaSessionConnection.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumCard.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumView.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/BottomBar.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/Controls.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/CurrentTrackInfo.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerOverlay.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/Queue.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/ToolBar.kt, app/src/main/java/me/vanpetegem/accentor/ui/tracks/TrackRow.kt
=> Make MediaSessionConnection not a ViewModel

app/src/main/java/me/vanpetegem/accentor/media/MusicService.kt
=> Go back to first track after playlist ends

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumGrid.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumsViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistGrid.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistsViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/util/FastScrollableGrid.kt, app/src/main/res/values/strings.xml
=> Allow searching artists and albums

app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt
=> Fix colors of search bar in dark mode

app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt
=> Hide keyboard when pressing done

app/src/main/java/me/vanpetegem/accentor/ui/tracks/TrackRow.kt
=> Show unique `artist_id` and `name` pairs only once in TrackRow

app/build.gradle, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumView.kt
=> Show various artists in album view if no album artists

app/src/main/java/me/vanpetegem/accentor/ui/home/HomeFragment.kt, app/src/main/res/values/strings.xml
=> Show messages for empty states on home view

app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumCard.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumGrid.kt, app/src/main/java/me/vanpetegem/accentor/ui/albums/AlbumView.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistGrid.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistView.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeFragment.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/tracks/TrackRow.kt
=> Fix refresh button in toolbar using a different viewmodel instance than indicator

app/src/main/java/me/vanpetegem/accentor/data/tracks/Track.kt, app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistViewModel.kt
=> Sort tracks on artist view alphabetically

app/schemas/me.vanpetegem.accentor.data.AccentorDatabase/9.json, app/src/main/java/me/vanpetegem/accentor/api/plays/Play.kt, app/src/main/java/me/vanpetegem/accentor/data/AccentorDatabase.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/Album.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumDao.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/Artist.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/ArtistDao.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/ArtistRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/DbPlay.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/PlayDao.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/PlayRepository.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeFragment.kt, app/src/main/java/me/vanpetegem/accentor/ui/home/HomeViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainViewModel.kt, app/src/main/res/values/strings.xml
=> Add recently played artists and albums to home

app/src/main/java/me/vanpetegem/accentor/media/NotificationBuilder.kt
This made the app crash on Android 12.
=> Fix immutable flag not being passed in pending intent

app/src/main/java/me/vanpetegem/accentor/ui/artists/ArtistView.kt
This regressed after the recent coil update.
=> Crop artist image instead of default fit

app/src/main/java/me/vanpetegem/accentor/media/MusicService.kt
=> Make sure tracks with no cover art can be played

app/src/main/java/me/vanpetegem/accentor/data/preferences/PreferencesDataSource.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/preferences/PreferencesActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/preferences/PreferencesViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/util/Event.kt, app/src/main/res/values/strings.xml
=> Give user more insight into sync status

app/src/main/java/me/vanpetegem/accentor/api/album/Album.kt, app/src/main/java/me/vanpetegem/accentor/api/artist/Artist.kt, app/src/main/java/me/vanpetegem/accentor/api/codecconversion/CodecConversion.kt, app/src/main/java/me/vanpetegem/accentor/api/plays/Play.kt, app/src/main/java/me/vanpetegem/accentor/api/track/Track.kt, app/src/main/java/me/vanpetegem/accentor/api/user/User.kt, app/src/main/java/me/vanpetegem/accentor/api/util/Util.kt
=> Retry fetches of resource index a few times with exponential backoff

app/src/main/java/me/vanpetegem/accentor/media/MediaSessionConnection.kt, app/src/main/java/me/vanpetegem/accentor/media/MusicService.kt
=> Make previous seek to start if far enough along in a track

app/src/main/java/me/vanpetegem/accentor/data/AccentorDatabase.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/artists/ArtistRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/plays/PlayRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackRepository.kt
=> Make sure views using database results are reactive

app/src/main/java/me/vanpetegem/accentor/ui/player/Controls.kt
=> Fix wonky player progress bar

app/schemas/me.vanpetegem.accentor.data.AccentorDatabase/12.json, app/src/main/java/me/vanpetegem/accentor/api/playlist/Playlist.kt, app/src/main/java/me/vanpetegem/accentor/data/AccentorDatabase.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumDao.kt, app/src/main/java/me/vanpetegem/accentor/data/albums/AlbumRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/Access.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/ApiPlaylist.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/DbPlaylist.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/Playlist.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/PlaylistDao.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/PlaylistRepository.kt, app/src/main/java/me/vanpetegem/accentor/data/playlists/PlaylistType.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackDao.kt, app/src/main/java/me/vanpetegem/accentor/data/tracks/TrackRepository.kt, app/src/main/java/me/vanpetegem/accentor/media/MediaSessionConnection.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainActivity.kt, app/src/main/java/me/vanpetegem/accentor/ui/main/MainViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/playlists/PlaylistList.kt, app/src/main/java/me/vanpetegem/accentor/ui/playlists/PlaylistView.kt, app/src/main/java/me/vanpetegem/accentor/ui/playlists/PlaylistViewModel.kt, app/src/main/java/me/vanpetegem/accentor/ui/playlists/PlaylistsViewModel.kt, app/src/main/java/me/vanpetegem/accentor/util/FuelGson.kt, app/src/main/java/me/vanpetegem/accentor/util/RoomTypeConverters.kt, app/src/main/res/drawable/ic_menu_playlists.xml, app/src/main/res/values/strings.xml
=> Add playlist support

app/build.gradle, build.gradle
=> Bump compose compiler

app/build.gradle
Lints should not activate because time has passed.
=> Disable android gradle plugin version lint

app/src/main/java/me/vanpetegem/accentor/ui/player/PlayerOverlay.kt
=> Don't draw player view if drawer is closed
